"""Generate the paper language validation table from template metadata."""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from scripts.update_readme_table import (  # noqa: E402
    LanguageValidation,
    _included_languages,
    collect_language_validation,
)


def _latex_cell(value: str) -> str:
    escapes = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "\n": " ",
    }
    return "".join(escapes.get(char, char) for char in value)


def render_latex_table(languages: list[LanguageValidation]) -> str:
    """One row per language, with single-line cells; requires amssymb."""
    lines = [
        "% Generated by paper/update_language_table.py; do not edit.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llccll}",
        r"\hline",
        r"Language & Human review & Comp. validated & Error analysis & Initial translation model & Source lang. \\",
        r"\hline",
    ]
    for lang in _included_languages(languages):
        values = [
            _latex_cell(lang.language),
            _latex_cell(lang.human.removeprefix("by ")),
            r"$\checkmark$",
            r"$\checkmark$" if lang.error else "",
            _latex_cell(lang.model),
            _latex_cell(lang.source_language),
        ]
        lines.append(" & ".join(values) + r" \\")
    lines.extend(
        [
            r"\hline",
            r"\end{tabular}",
            r"\caption{Human-validated languages and reviews in progress, alongside the English originals. Computational validation is enforced by CI. Error analysis is marked only when complete for all active templates.}",
            r"\label{tab:language-validation}",
            r"\end{table*}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--templates-root", type=Path, default=Path("src/multilingual_gsm_symbolic/data/templates"))
    parser.add_argument("--latex", type=Path, default=Path("paper/language_validation.tex"))
    args = parser.parse_args()
    languages = collect_language_validation(args.templates_root)
    args.latex.parent.mkdir(parents=True, exist_ok=True)
    args.latex.write_text(render_latex_table(languages), encoding="utf-8", newline="\n")
    print(f"Updated {args.latex}")


if __name__ == "__main__":
    main()
